#!/usr/bin/perl
# This script is use for annotated peaks with All_annotation generated by "Unique_annotation_maker.pl".
# perl Peak_annotater.pl All_mRNA Beta_summary 4500



open FILE, $ARGV[0];
my $first1=<FILE>;
my %annotation;
print "loading annotation table\n";
while (defined (my $line = <FILE>) ) {
  	chomp $line;#delete the /n of each line
  	my @parameters=split("\t",$line);
    my $chr=$parameters[0];
    my $strand=$parameters[2];
    my $position=$parameters[1];
    $annotation{$chr}{$position}{$strand}=$line;
} 
close FILE;

open FILE, $ARGV[1];
my $first2=<FILE>;
my $peaks;
print "loading peaks table\n";
while (defined (my $line = <FILE>) ) {
  	chomp $line;#delete the /n of each line
  	my @parameters=split(" ",$line);
    my $chr=$parameters[0];
    my $strand=$parameters[1];
    my $pos=$parameters[2];
    $peaks{$chr}{$pos}{$strand}="$parameters[3]\t$parameters[4]\t$parameters[6]\t$parameters[8]\t$parameters[10]";
} 
close FILE;


$cut_length=$ARGV[2];
my $filename=$ARGV[0];
my $filename2=$ARGV[1];
open ( my $outfile, ">$filename\_$filename2" ) or die;
print $outfile "Direction\tDistance\ttotal\tRead0.5\tRead2\tRead8\tRead32\tPeak\t$first1";
print "annotating peaks table\n";
foreach my $chr (sort keys %annotation){
	my @peak_list;
	my @strand_list;
	my @information_list;
	foreach my $peak_loc (sort {$a<=>$b} keys %{$peaks{$chr}}){
		foreach my $peak_strand (sort keys %{$peaks{$chr}{$peak_loc}}){
			push @peak_list,$peak_loc;
			push @strand_list,$peak_strand;
			push @information_list,$peaks{$chr}{$peak_loc}{$peak_strand};
		}
	}
	my $index=0;
	my $array_length=@peak_list;
	if ($array_length>5000) {
		print "Now annotating $chr\n";
	}
	foreach my $annotation_position (sort {$a<=>$b} keys %{$annotation{$chr}}){
		foreach my $annotation_strand (sort keys %{$annotation{$chr}{$annotation_position}}){
			my $record_check=0;
			for (my $var = $index; $var < $array_length; $var++) {
				if ($record_check eq 0 and $peak_list[$var]>$annotation_position-$cut_length) {
					$record_check=1;
					$index=$var;
				}
				if ($peak_list[$var]>$annotation_position+$cut_length) {
					last;
				}
				if ($peak_list[$var]>$annotation_position-$cut_length) {
					my $Direction;
					my $Distance;
					if ($strand_list[$var] eq $annotation_strand) {
						$Direction="sense";
					}else{
						$Direction="antisense";
					}
					if ($annotation_strand eq "+") {
						$Distance=$peak_list[$var]-$annotation_position;
					}else{
						$Distance=$annotation_position-$peak_list[$var];
					}
					print $outfile "$Direction\t$Distance\t$peaks{$chr}{$peak_list[$var]}{$strand_list[$var]}\t$peak_list[$var]\t$annotation{$chr}{$annotation_position}{$annotation_strand}\n";
				}
			}
		}
	}
}


close FILE;
close $outfile;
